"""Initial schema: documents, chunks, citations, audit log.

Written by hand rather than autogenerated: the extension, the HNSW index, the
tsvector trigger, and the RLS policies are all invisible to Alembic's model
comparison, and they are the parts that make retrieval work.

Revision ID: 0001
Revises:
Create Date: 2026-08-01
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

EMBEDDING_DIM = 1024

#: Tables carrying ingested corpus or run history. RLS is enabled on each; the
#: backend connects as a role that bypasses it, so this is defence in depth
#: against the Supabase Data API exposing a table we did not intend to publish.
TABLES = ("documents", "chunks", "citations", "audit_log")


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "documents",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("kind", sa.String(16), nullable=False),
        sa.Column("title", sa.Text, nullable=False),
        sa.Column("source_ref", sa.String(255), nullable=False),
        sa.Column("source_url", sa.Text),
        sa.Column("content_hash", sa.String(64), nullable=False),
        sa.Column(
            "meta",
            postgresql.JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint("kind", "source_ref", name="uq_documents_kind_source_ref"),
    )
    op.create_index("ix_documents_kind", "documents", ["kind"])
    op.create_index("ix_documents_content_hash", "documents", ["content_hash"])

    op.create_table(
        "chunks",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "document_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("documents.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("ordinal", sa.Integer, nullable=False),
        sa.Column("label", sa.String(255)),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("token_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("embedding", Vector(EMBEDDING_DIM)),
        sa.Column("tsv", postgresql.TSVECTOR),
        sa.Column(
            "meta",
            postgresql.JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint("document_id", "ordinal", name="uq_chunks_document_ordinal"),
        sa.CheckConstraint("token_count >= 0", name="ck_chunks_token_count_non_negative"),
    )
    op.create_index("ix_chunks_document_id", "chunks", ["document_id"])

    # Lexical half of hybrid retrieval. 'english' is an imperfect fit for Indian
    # legal English but handles the Latin-script statutory vocabulary well; the
    # vector half covers the semantic gap.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION chunks_tsv_update() RETURNS trigger AS $$
        BEGIN
          NEW.tsv := to_tsvector(
            'english',
            coalesce(NEW.label, '') || ' ' || coalesce(NEW.content, '')
          );
          RETURN NEW;
        END
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER chunks_tsv_trigger
        BEFORE INSERT OR UPDATE OF content, label ON chunks
        FOR EACH ROW EXECUTE FUNCTION chunks_tsv_update()
        """
    )
    op.execute("CREATE INDEX ix_chunks_tsv ON chunks USING GIN (tsv)")

    # HNSW rather than IVFFlat: better recall/latency at this corpus size and no
    # training step, so it stays correct as the corpus grows incrementally.
    op.execute(
        """
        CREATE INDEX ix_chunks_embedding_hnsw ON chunks
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
        """
    )

    op.create_table(
        "citations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "source_document_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("documents.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "target_document_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("documents.id", ondelete="SET NULL"),
        ),
        sa.Column("target_ref", sa.String(255), nullable=False),
        sa.Column("context", sa.Text),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint("source_document_id", "target_ref", name="uq_citations_source_target"),
        sa.CheckConstraint(
            "source_document_id <> target_document_id",
            name="ck_citations_no_self_reference",
        ),
    )
    op.create_index("ix_citations_source", "citations", ["source_document_id"])
    op.create_index("ix_citations_target", "citations", ["target_document_id"])

    op.create_table(
        "audit_log",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("run_id", sa.String(64), nullable=False),
        sa.Column("module", sa.String(32), nullable=False),
        sa.Column("event", sa.String(64), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index("ix_audit_log_run_id", "audit_log", ["run_id"])
    op.create_index("ix_audit_log_created_at", "audit_log", ["created_at"])

    # No policies are defined, so RLS denies everything by default to the
    # anon/authenticated roles the Data API uses. The backend's connection role
    # bypasses RLS, which is what we want: this corpus is served through the
    # API, not queried directly by browsers.
    for table in TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    op.drop_table("audit_log")
    op.drop_table("citations")
    op.execute("DROP INDEX IF EXISTS ix_chunks_embedding_hnsw")
    op.execute("DROP INDEX IF EXISTS ix_chunks_tsv")
    op.execute("DROP TRIGGER IF EXISTS chunks_tsv_trigger ON chunks")
    op.execute("DROP FUNCTION IF EXISTS chunks_tsv_update()")
    op.drop_table("chunks")
    op.drop_table("documents")
